// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/entities.proto

package grpc_user_go // import "github.com/aagea/grpc-user-go"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   *UserID   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string    `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string    `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Friends              []*UserID `protobuf:"bytes,4,rep,name=friends,proto3" json:"friends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_entities_9382e5791f2a24e5, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() *UserID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetFriends() []*UserID {
	if m != nil {
		return m.Friends
	}
	return nil
}

type UserID struct {
	Organization         string   `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_entities_9382e5791f2a24e5, []int{1}
}
func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (dst *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(dst, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *UserID) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*UserID)(nil), "user.UserID")
}

func init() { proto.RegisterFile("user/entities.proto", fileDescriptor_entities_9382e5791f2a24e5) }

var fileDescriptor_entities_9382e5791f2a24e5 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2d, 0x4e, 0x2d,
	0xd2, 0x4f, 0xcd, 0x2b, 0xc9, 0x2c, 0xc9, 0x4c, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x01, 0x09, 0x2a, 0x75, 0x30, 0x72, 0xb1, 0x84, 0x16, 0xa7, 0x16, 0x09, 0xc9, 0x70, 0x31,
	0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xe8, 0x81, 0xe4, 0xf4, 0x40, 0xe2,
	0x9e, 0x2e, 0x41, 0x4c, 0x99, 0x29, 0x42, 0xb2, 0x5c, 0x5c, 0x69, 0x99, 0x45, 0xc5, 0x25, 0xf1,
	0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x9c, 0x60, 0x11, 0xbf, 0xc4,
	0xdc, 0x54, 0x21, 0x69, 0x2e, 0xce, 0x9c, 0x44, 0x98, 0x2c, 0x33, 0x58, 0x96, 0x03, 0x24, 0x00,
	0x96, 0x54, 0xe3, 0x62, 0x4f, 0x2b, 0xca, 0x4c, 0xcd, 0x4b, 0x29, 0x96, 0x60, 0x51, 0x60, 0xc6,
	0x30, 0x1e, 0x26, 0xa9, 0xe4, 0xc1, 0xc5, 0x06, 0x11, 0x12, 0x52, 0xe2, 0xe2, 0xc9, 0x2f, 0x4a,
	0x4f, 0xcc, 0xcb, 0xac, 0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0x03, 0xbb, 0x8a, 0x33, 0x08, 0x45, 0x4c,
	0x48, 0x8a, 0x8b, 0x03, 0x64, 0x0a, 0x92, 0x7b, 0xe0, 0x7c, 0x27, 0xf9, 0x28, 0xd9, 0xf4, 0xcc,
	0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xc4, 0xc4, 0xf4, 0xd4, 0x44, 0xfd, 0xf4,
	0xa2, 0x82, 0x64, 0x5d, 0x90, 0x0a, 0xdd, 0xf4, 0xfc, 0x24, 0x36, 0x70, 0x10, 0x18, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x17, 0x62, 0xdc, 0x14, 0x19, 0x01, 0x00, 0x00,
}
